/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class JInternalFrameRegisterSubject extends javax.swing.JInternalFrame {

    private String subject;
    private String type;
    private float partial1;
    private float partial2;
    private float partial3;
    
    private ListSubject list = new ListSubject(null, 0);
    
    //VARIABLES PARA CALCULAR EL PARCIAL 3
    private float p1;
    private float p2;
    private float p3;
    private float avarage1;
    private float avarage2;
    private float avarage3;
    private float result;
    
    
    public JInternalFrameRegisterSubject() {
        initComponents();
        
        
        //METODO PARA AGREGAR DATOS A LA TABLA 
        
        Weighing[] weighing = new Weighing[3];
        for(int i = 0; i<3; i++){
            weighing[i] = new Weighing(null, 0, 0, 0);
        }
        weighing[0] = new Weighing("Tipo A", 33, 33, 34);
        weighing[1] = new Weighing("Tipo B", 20, 35, 45);
        weighing[2] = new Weighing("Tipo c", 25, 25, 50);
        
        DefaultTableModel model = new DefaultTableModel();
        
        String[] head = {"Tipo", "Parcial 1", "Parcial 2", "Parcial 3"};
        
        model.setColumnIdentifiers(head);
        
        for(int i = 0; i<weighing.length; i++){
            Object[] object = new Object[10];
            object[0] = weighing[i].getType();
            object[1] = weighing[i].getNum1();
            object[2] = weighing[i].getNum2();
            object[3] = weighing[i].getNum3();
            model.addRow(object);
        }
        
        jTable1.setModel(model);
        
        //METODO PARA COLOCAR IMAGEN EN EL CURSOR 
        
        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\Cursores\\Cursor2.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        c = tk.createCustomCursor(img.getImage(), new Point(1,1), null);
        
        jButtonCalculate.setCursor(c);

        jRadioButtonTypeA.setCursor(c);
        jRadioButtonTypeB.setCursor(c);
        jRadioButtonTypeC.setCursor(c);
        
        jCheckBox1.setCursor(c);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonTypeA = new javax.swing.JRadioButton();
        jRadioButtonTypeB = new javax.swing.JRadioButton();
        jRadioButtonTypeC = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNameSubject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPartial1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPartial2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonCalculate = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de materia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Ponderacion: ");

        buttonGroup1.add(jRadioButtonTypeA);
        jRadioButtonTypeA.setText("Tipo A");

        buttonGroup1.add(jRadioButtonTypeB);
        jRadioButtonTypeB.setText("Tipo B");
        jRadioButtonTypeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTypeBActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTypeC);
        jRadioButtonTypeC.setText("Tipo C");

        jLabel3.setText("Nombre de la materia: ");

        jTextFieldNameSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameSubjectActionPerformed(evt);
            }
        });

        jLabel4.setText("Parcial 1: ");

        jTextFieldPartial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPartial1ActionPerformed(evt);
            }
        });
        jTextFieldPartial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial1KeyTyped(evt);
            }
        });

        jLabel5.setText("Parcial 2: ");

        jTextFieldPartial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial2KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("*Nota");

        jLabel7.setText("Si todavia no realizas el parcial 2, marca la casilla");

        jButtonCalculate.setText("Calcular");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jRadioButtonTypeA)
                                        .addComponent(jRadioButtonTypeB)
                                        .addComponent(jRadioButtonTypeC))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldPartial1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldPartial2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                            .addComponent(jButtonCalculate))
                                        .addComponent(jTextFieldNameSubject)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonTypeA))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTypeB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTypeC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPartial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCalculate)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPartial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTypeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTypeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTypeBActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        if(jRadioButtonTypeA.isSelected()){
            type = "Tipo A";
            p1 = 33;
            p2 = 33;
            p3 = 34;
        }else if(jRadioButtonTypeB.isSelected()){
            type = "Tipo B";
            p1 = 20;
            p2 = 35;
            p3 = 45;
        }else if(jRadioButtonTypeC.isSelected()){
            type = "Tipo C";
            p1 = 25;
            p2 = 25;
            p3 = 50;
        }
        
        subject = jTextFieldNameSubject.getText();
        
        partial1 = Integer.parseInt(jTextFieldPartial1.getText());
        
        if(jTextFieldPartial2.getText().isEmpty()){
            partial2 = 0;
        }else{
            partial2 = Integer.parseInt(jTextFieldPartial2.getText());
        }
        
        //CALCULO DEL PARCIAL 3
        if(!jCheckBox1.isSelected()){
            avarage1 = (partial1 * p1)/100;
            avarage2 = (partial2 * p2)/100;
            result = (avarage1 + avarage2)-70;
            partial3 = (result * 100)/p3;

            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial3)+" en el tercer parcial para pasar con 70");
        }else{
        //CALCULO DEL PARCIAL 3    
            avarage1 = (partial1 * p1)/100;
            result = (avarage1 - 70)/2;
            partial2 = (result * 100)/p2;
            partial3 = (result * 100)/p3;
            
            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial2)+" en el Segundo parcial para pasar con 70");
            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial3)+" en el tercer parcial para pasar con 70");
        }
        
        list.add(subject, type, partial1, Math.abs(partial2), Math.abs(partial3));
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextFieldPartial1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial1KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(jTextFieldPartial1.getText().length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPartial1KeyTyped

    private void jTextFieldPartial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPartial1ActionPerformed
        jTextFieldPartial2.requestFocus();
    }//GEN-LAST:event_jTextFieldPartial1ActionPerformed

    private void jTextFieldNameSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameSubjectActionPerformed
        jTextFieldPartial1.requestFocus();
    }//GEN-LAST:event_jTextFieldNameSubjectActionPerformed

    private void jTextFieldPartial2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial2KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(jTextFieldPartial2.getText().length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPartial2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonTypeA;
    private javax.swing.JRadioButton jRadioButtonTypeB;
    private javax.swing.JRadioButton jRadioButtonTypeC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNameSubject;
    private javax.swing.JTextField jTextFieldPartial1;
    private javax.swing.JTextField jTextFieldPartial2;
    // End of variables declaration//GEN-END:variables
}
