/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class JInternalFrameRegisterSubject extends javax.swing.JInternalFrame {

    private String subject;
    private String type;
    private float partial1;
    private float partial2;
    private float partial3;
    
    private ListSubject list = new ListSubject(null, 0);
    
    //VARIABLES PARA CALCULAR EL PARCIAL 3
    private float p1;
    private float p2;
    private float p3;
    private float avarage1;
    private float avarage2;
    private float avarage3;
    private float result;
    
    
    public JInternalFrameRegisterSubject() {
        initComponents();
        
        
        //METODO PARA AGREGAR DATOS A LA TABLA 
        
        Weighing[] weighing = new Weighing[3];
        for(int i = 0; i<3; i++){
            weighing[i] = new Weighing(null, 0, 0, 0);
        }
        weighing[0] = new Weighing("Tipo A", 33, 33, 34);
        weighing[1] = new Weighing("Tipo B", 20, 35, 45);
        weighing[2] = new Weighing("Tipo c", 25, 25, 50);
        
        DefaultTableModel model = new DefaultTableModel();
        
        String[] head = {"Tipo", "Parcial 1", "Parcial 2", "Parcial 3"};
        
        model.setColumnIdentifiers(head);
        
        for(int i = 0; i<weighing.length; i++){
            Object[] object = new Object[10];
            object[0] = weighing[i].getType();
            object[1] = weighing[i].getNum1();
            object[2] = weighing[i].getNum2();
            object[3] = weighing[i].getNum3();
            model.addRow(object);
        }
        
        jTable1.setModel(model);
        
        //METODO PARA COLOCAR IMAGEN EN EL CURSOR 
        
        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\Cursores\\Cursor2.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        c = tk.createCustomCursor(img.getImage(), new Point(1,1), null);
        
        jButtonCalculate.setCursor(c);

        jRadioButtonTypeA.setCursor(c);
        jRadioButtonTypeB.setCursor(c);
        jRadioButtonTypeC.setCursor(c);
        
        jCheckBox1.setCursor(c);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonTypeA1 = new javax.swing.JRadioButton();
        jRadioButtonTypeB1 = new javax.swing.JRadioButton();
        jRadioButtonTypeC1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNameSubject1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPartial3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPartial4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonCalculate1 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonTypeA = new javax.swing.JRadioButton();
        jRadioButtonTypeB = new javax.swing.JRadioButton();
        jRadioButtonTypeC = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNameSubject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPartial1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPartial2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de materia");

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Registro de materia");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setText("Ponderacion: ");

        buttonGroup1.add(jRadioButtonTypeA1);
        jRadioButtonTypeA1.setText("Tipo A");

        buttonGroup1.add(jRadioButtonTypeB1);
        jRadioButtonTypeB1.setText("Tipo B");
        jRadioButtonTypeB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTypeB1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTypeC1);
        jRadioButtonTypeC1.setText("Tipo C");

        jLabel10.setText("Nombre de la materia: ");

        jTextFieldNameSubject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameSubject1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Parcial 1: ");

        jTextFieldPartial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPartial3ActionPerformed(evt);
            }
        });
        jTextFieldPartial3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial3KeyTyped(evt);
            }
        });

        jLabel12.setText("Parcial 2: ");

        jTextFieldPartial4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial4KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("*Nota");

        jLabel14.setText("Si todavia no realizas el parcial 2, marca la casilla");

        jButtonCalculate1.setText("Calcular");
        jButtonCalculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculate1ActionPerformed(evt);
            }
        });

        jButton2.setText("Recomendaciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel8))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jRadioButtonTypeA1)
                                        .addComponent(jRadioButtonTypeB1)
                                        .addComponent(jRadioButtonTypeC1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldPartial3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(35, 35, 35)
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldPartial4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonCalculate1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addComponent(jTextFieldNameSubject1)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonTypeA1))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNameSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonTypeB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonTypeC1))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jButton2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldPartial4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCalculate1)))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPartial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jCheckBox2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 131, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 377, 83));

        jLabel2.setText("Ponderacion: ");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        buttonGroup1.add(jRadioButtonTypeA);
        jRadioButtonTypeA.setText("Tipo A");
        jDesktopPane1.add(jRadioButtonTypeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        buttonGroup1.add(jRadioButtonTypeB);
        jRadioButtonTypeB.setText("Tipo B");
        jRadioButtonTypeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTypeBActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jRadioButtonTypeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        buttonGroup1.add(jRadioButtonTypeC);
        jRadioButtonTypeC.setText("Tipo C");
        jDesktopPane1.add(jRadioButtonTypeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel3.setText("Nombre de la materia: ");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 288, -1));

        jTextFieldNameSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameSubjectActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTextFieldNameSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 288, -1));

        jLabel4.setText("Parcial 1: ");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTextFieldPartial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPartial1ActionPerformed(evt);
            }
        });
        jTextFieldPartial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial1KeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPartial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, -1));

        jLabel5.setText("Parcial 2: ");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jTextFieldPartial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPartial2KeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPartial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 50, -1));

        jButton1.setText("Recomendaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jButtonCalculate.setText("Calcular");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel7.setText("Si todavia no realizas el parcial 2, marca la casilla");
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));
        jDesktopPane1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("*Nota");
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 370, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTypeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTypeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTypeBActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        if(jRadioButtonTypeA.isSelected()){
            type = "Tipo A";
            p1 = 33;
            p2 = 33;
            p3 = 34;
        }else if(jRadioButtonTypeB.isSelected()){
            type = "Tipo B";
            p1 = 20;
            p2 = 35;
            p3 = 45;
        }else if(jRadioButtonTypeC.isSelected()){
            type = "Tipo C";
            p1 = 25;
            p2 = 25;
            p3 = 50;
        }
        
        subject = jTextFieldNameSubject.getText();
        
        partial1 = Integer.parseInt(jTextFieldPartial1.getText());
        
        if(jTextFieldPartial2.getText().isEmpty()){
            partial2 = 0;
        }else{
            partial2 = Integer.parseInt(jTextFieldPartial2.getText());
        }
        
        //CALCULO DEL PARCIAL 3
        if(!jCheckBox1.isSelected()){
            avarage1 = (partial1 * p1)/100;
            avarage2 = (partial2 * p2)/100;
            result = (avarage1 + avarage2)-70;
            partial3 = (result * 100)/p3;

            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial3)+" en el tercer parcial para pasar con 70");
        }else{
        //CALCULO DEL PARCIAL 3    
            avarage1 = (partial1 * p1)/100;
            result = (avarage1 - 70)/2;
            partial2 = (result * 100)/p2;
            partial3 = (result * 100)/p3;
            
            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial2)+" en el Segundo parcial para pasar con 70");
            JOptionPane.showMessageDialog(null, "Nececitas "+Math.abs(partial3)+" en el tercer parcial para pasar con 70");
        }
        
        list.add(subject, type, partial1, Math.abs(partial2), Math.abs(partial3));
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextFieldPartial1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial1KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(jTextFieldPartial1.getText().length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPartial1KeyTyped

    private void jTextFieldPartial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPartial1ActionPerformed
        jTextFieldPartial2.requestFocus();
    }//GEN-LAST:event_jTextFieldPartial1ActionPerformed

    private void jTextFieldNameSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameSubjectActionPerformed
        jTextFieldPartial1.requestFocus();
    }//GEN-LAST:event_jTextFieldNameSubjectActionPerformed

    private void jTextFieldPartial2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial2KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(jTextFieldPartial2.getText().length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPartial2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reporte vReporte = new Reporte(list);
        jDesktopPane3.add(vReporte);
        vReporte.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonTypeB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTypeB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTypeB1ActionPerformed

    private void jTextFieldNameSubject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameSubject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameSubject1ActionPerformed

    private void jTextFieldPartial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPartial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPartial3ActionPerformed

    private void jTextFieldPartial3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPartial3KeyTyped

    private void jTextFieldPartial4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPartial4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPartial4KeyTyped

    private void jButtonCalculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalculate1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonCalculate1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonTypeA;
    private javax.swing.JRadioButton jRadioButtonTypeA1;
    private javax.swing.JRadioButton jRadioButtonTypeB;
    private javax.swing.JRadioButton jRadioButtonTypeB1;
    private javax.swing.JRadioButton jRadioButtonTypeC;
    private javax.swing.JRadioButton jRadioButtonTypeC1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldNameSubject;
    private javax.swing.JTextField jTextFieldNameSubject1;
    private javax.swing.JTextField jTextFieldPartial1;
    private javax.swing.JTextField jTextFieldPartial2;
    private javax.swing.JTextField jTextFieldPartial3;
    private javax.swing.JTextField jTextFieldPartial4;
    // End of variables declaration//GEN-END:variables
}
