/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Derek
 */
public class repasoPreguntasUI extends javax.swing.JInternalFrame {
    private ListaPreguntas listaPreguntas;
    NodoPregunta preguntaActual;
    int puntos = 0;
    /**
     * Creates new form repasoPreguntasUI
     */
    public repasoPreguntasUI(ListaPreguntas listaPeguntas) {
        this.listaPreguntas = listaPeguntas;
        initComponents();
        
        
         if(listaPreguntas.getTamaño() == 0) {
    JOptionPane.showMessageDialog(this, "No hay preguntas disponibles", "Aviso", JOptionPane.WARNING_MESSAGE);
} else {
    preguntaActual = listaPreguntas.getSiguientePregunta();
    if(preguntaActual != null) {
        jTpregunta.setText(preguntaActual.getPregunta());
        jTrespuesta.setText("");  // Limpiar la respuesta
    }
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTpregunta = new javax.swing.JTextField();
        jBcorrecto = new javax.swing.JButton();
        jTrespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBincorrecto = new javax.swing.JButton();
        jBrespuesta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTpuntos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTpregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpreguntaActionPerformed(evt);
            }
        });

        jBcorrecto.setText("Correcto");
        jBcorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcorrectoActionPerformed(evt);
            }
        });

        jTrespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrespuestaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pregunta");

        jBincorrecto.setText("Incorrecto");
        jBincorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincorrectoActionPerformed(evt);
            }
        });

        jBrespuesta.setText("Mostrar Respuesta");
        jBrespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrespuestaActionPerformed(evt);
            }
        });

        jLabel2.setText("Puntos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTpregunta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTrespuesta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBincorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jBcorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jBrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTpuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBrespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcorrecto)
                    .addComponent(jBincorrecto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTpuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcorrectoActionPerformed
        // TODO add your handling code here:
         puntos += 1;
    jTpuntos.setText(String.valueOf(puntos));
    cargarSiguientePregunta();
    }//GEN-LAST:event_jBcorrectoActionPerformed

    private void jTpreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpreguntaActionPerformed

    
    private void cargarSiguientePregunta() {
    preguntaActual = listaPreguntas.getSiguientePregunta();
    
    if(preguntaActual != null) {
        jTpregunta.setText(preguntaActual.getPregunta());
        jTrespuesta.setText(""); // Limpiar respuesta
    } else {
        int opcion = JOptionPane.showConfirmDialog(this, 
                "No hay más preguntas. ¿Quieres comenzar de nuevo?", 
                "Fin del repaso", 
                JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION) {
            listaPreguntas.reiniciarContador();
            puntos = 0;
            jTpuntos.setText(String.valueOf(puntos));
            cargarSiguientePregunta();
        }
    }
}
    
    private void jTrespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrespuestaActionPerformed

    private void jBincorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincorrectoActionPerformed
        // TODO add your handling code here:
         puntos -= 1;
    jTpuntos.setText(String.valueOf(puntos));
    cargarSiguientePregunta();
    }//GEN-LAST:event_jBincorrectoActionPerformed

    private void jBrespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrespuestaActionPerformed
        // TODO add your handling code here:
      if(preguntaActual != null) {
        jTrespuesta.setText(preguntaActual.getRespuesta());
    }
      
      
    }//GEN-LAST:event_jBrespuestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcorrecto;
    private javax.swing.JButton jBincorrecto;
    private javax.swing.JButton jBrespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTpregunta;
    private javax.swing.JTextField jTpuntos;
    private javax.swing.JTextField jTrespuesta;
    // End of variables declaration//GEN-END:variables
}
